#!/usr/bin/env python3
"""Fetch, subset and pack the fonts the app ships.

This is NOT a build step for the app: `index.html` runs straight from the
files in `fonts/`, which are committed. Run this only when a font needs to
be added, updated or re-subset.

    pip install fonttools brotli
    python tools/build-fonts.py

It writes:
    fonts/*.woff2            faces used by the page itself
    fonts/embedded-fonts.js  the same faces the templates need, as base64
                             data URIs, so they can be baked into an SVG
                             before it is rasterised (an SVG loaded into an
                             <img> cannot see @font-face rules of its host).
"""

import base64
import io
import os
import shutil
import tarfile
import urllib.request

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONTS = os.path.join(ROOT, "fonts")
CACHE = os.path.join(ROOT, ".fontcache")

# Latin-1 plus Latin Extended-A (Czech, Polish, French, German …), the
# punctuation Affinity emits and the fi/fl ligatures found in the templates.
UNICODES = (
    "U+0020-007E,U+00A0-00FF,U+0100-017F,U+0192,U+02C6,U+02DC,"
    "U+2013-2014,U+2018-201A,U+201C-201E,U+2020-2022,U+2026,U+2030,"
    "U+2039-203A,U+2044,U+20AC,U+2122,U+2212,U+FB01-FB02"
)

METROPOLIS = "https://cdn.jsdelivr.net/gh/dw5/Metropolis@master/Fonts/TrueType/Metropolis-%s.ttf"
LIBERATION = "https://github.com/liberationfonts/liberation-fonts/files/7261482/liberation-fonts-ttf-2.1.5.tar.gz"
FONTSOURCE = "https://cdn.jsdelivr.net/npm/@fontsource/%s@5/files/%s.woff2"

# Faces the page uses for its own interface; taken from Fontsource as-is.
UI_FACES = [
    ("archivo", "archivo-latin-500-normal"),
    ("archivo", "archivo-latin-ext-500-normal"),
    ("archivo", "archivo-latin-700-normal"),
    ("archivo", "archivo-latin-ext-700-normal"),
    ("ibm-plex-sans", "ibm-plex-sans-latin-400-normal"),
    ("ibm-plex-sans", "ibm-plex-sans-latin-ext-400-normal"),
    ("ibm-plex-sans", "ibm-plex-sans-latin-600-normal"),
    ("ibm-plex-sans", "ibm-plex-sans-latin-ext-600-normal"),
]

# Faces the templates reference, keyed by the name used in the baked
# @font-face block. Metropolis is the club's face; Liberation Sans stands in
# for Arial, which is metrically identical but cannot be redistributed.
TEMPLATE_FACES = [
    ("Metropolis", "400", "Metropolis-Regular.woff2"),
    ("Metropolis", "700", "Metropolis-Bold.woff2"),
    ("Liberation Sans", "400", "LiberationSans-Regular.woff2"),
]


def download(url, path):
    if os.path.exists(path):
        return path
    print("fetch", url)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    req = urllib.request.Request(url, headers={"User-Agent": "fracify-build"})
    with urllib.request.urlopen(req) as r, open(path, "wb") as f:
        shutil.copyfileobj(r, f)
    return path


def subset_to_woff2(src, dest):
    font = TTFont(src)
    options = subset.Options()
    options.flavor = "woff2"
    options.layout_features = ["*"]
    options.name_IDs = ["*"]
    options.notdef_outline = True
    options.recalc_bounds = True
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=subset.parse_unicodes(UNICODES))
    subsetter.subset(font)
    font.flavorData = None
    font.flavor = "woff2"
    font.save(dest)
    print("wrote %-34s %6d B" % (os.path.relpath(dest, ROOT), os.path.getsize(dest)))


def main():
    os.makedirs(FONTS, exist_ok=True)

    for style in ("Regular", "Bold"):
        src = download(METROPOLIS % style, os.path.join(CACHE, "Metropolis-%s.ttf" % style))
        subset_to_woff2(src, os.path.join(FONTS, "Metropolis-%s.woff2" % style))

    tar_path = download(LIBERATION, os.path.join(CACHE, "liberation.tar.gz"))
    with tarfile.open(tar_path) as tar:
        member = next(m for m in tar.getmembers() if m.name.endswith("LiberationSans-Regular.ttf"))
        data = tar.extractfile(member).read()
    subset_to_woff2(io.BytesIO(data), os.path.join(FONTS, "LiberationSans-Regular.woff2"))

    for package, name in UI_FACES:
        dest = os.path.join(FONTS, name + ".woff2")
        download(FONTSOURCE % (package, name), os.path.join(CACHE, name + ".woff2"))
        shutil.copyfile(os.path.join(CACHE, name + ".woff2"), dest)
        print("wrote %-34s %6d B" % (os.path.relpath(dest, ROOT), os.path.getsize(dest)))

    lines = [
        "// Generated by tools/build-fonts.py - do not edit by hand.",
        "// The faces the SVG templates reference, as base64 data URIs. They are",
        "// inlined into a template's <defs> before it is rasterised, because an",
        "// SVG loaded into an <img> is an isolated document and cannot see the",
        "// @font-face rules of the page that loaded it.",
        "window.FRACIFY_FONTS = [",
    ]
    for family, weight, filename in TEMPLATE_FACES:
        with open(os.path.join(FONTS, filename), "rb") as f:
            b64 = base64.b64encode(f.read()).decode("ascii")
        lines.append("  {")
        lines.append("    family: %s," % js_string(family))
        lines.append("    weight: %s," % js_string(weight))
        lines.append("    src: 'data:font/woff2;base64,%s'" % b64)
        lines.append("  },")
    lines.append("];")
    out = os.path.join(FONTS, "embedded-fonts.js")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %-34s %6d B" % (os.path.relpath(out, ROOT), os.path.getsize(out)))


def js_string(value):
    return "'" + value.replace("\\", "\\\\").replace("'", "\'") + "'"


if __name__ == "__main__":
    main()
